Fix error handling in CLI
talaia-labs/rust-teos pull request #225
Opened 2023-07-03 22:14 UTC by optimm

2023-07-03 22:28 UTC, sr-gi commented
Add a description / rationale for the change

2023-07-06 18:29 UTC, sr-gi reviewed
Looks good, but I think it may be worth creating a function to encapsulate the printing + exit logic.

2023-07-24 15:27 UTC, sr-gi commented
> Looks good, but I think it may be worth creating a function to encapsulate the printing + exit logic.

@optimm any progress on this?

2023-07-27 19:40 UTC, sr-gi requested changes
Needs rebasing

2023-07-27 19:40 UTC, sr-gi commented on teos/src/cli.rs
> +fn handle_error<T: std::fmt::Display>(error: T) {
Place it on top of main, add minimal docs (`///`) for it.

2023-07-31 15:25 UTC, sr-gi requested changes
Minor comment inline.

Squash all commits.

2023-08-04 20:12 UTC, sr-gi commented
ACK [380c0d9](https://github.com/talaia-labs/rust-teos/pull/225/commits/380c0d9df68f5c61ac41fa364fdd96664ffd8d02)

2023-08-04 20:13 UTC, sr-gi approved these changes

2023-08-05 07:16 UTC, mariocynicys approved these changes

2023-08-07 14:29 UTC, sr-gi commented
@optimm we require commits to be signed in order to be merged to master. Check the docs on how to sign commits and rebase

2023-08-10 17:21 UTC, merged